# Generated by Django 4.0.5 on 2022-06-18 17:32

from django.db import migrations, models
import urlshortner.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CutDownUrl",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origin_url", models.URLField()),
                (
                    "shorten_key",
                    models.CharField(
                        db_index=True,
                        default=urlshortner.models.generate_random_string,
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
