# Generated by Django 4.0.5 on 2022-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortner", "0002_alter_cutdownurl_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cutdownurl",
            name="id",
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
