# Generated by Django 4.0.5 on 2022-06-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortner", "0003_alter_cutdownurl_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CutDownUrl",
            new_name="ShortenURL",
        ),
    ]
